<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Events\PostCreated;

class Post extends Model
{
    use HasFactory;
    protected $dispatchesEvents = [
        'created' => PostCreated::class,
    ];

//    public static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//        static::created(function($post){
//            \Mail::to($post->user->email)->send(
//                new PostCreated($post)
//            );
//        });
//
//    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function user(){
        return $this->belongsTo('App\Models\User');
    }

    public function tags(){
        return$this->belongsToMany('App\Models\Tag');
    }

}
